apiVersion: batch/v1
kind: Job
metadata:
  name: "hl2-ping-tests"
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    #argocd.argoproj.io/sync-wave: "0"
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: main
          image: ghcr.io/chestercodes/hl2-ping/{{ .Values.tests_image_name }}:{{ .Values.image_tag }}
          env:
          - name: DB_HOST
            value: "maindb"
          - name: DB_DATABASE
            value: "pingapp"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: maindb-ping
                key: ping-api-username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: maindb-ping
                key: ping-api-password

      restartPolicy: Never
  backoffLimit: 1
