apiVersion: v1
kind: Service
metadata:
  name: hlping-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: hlping
    tier: backend
