name: Build and publish images
on:
  push:
    paths:
      - 'app/**/*'
    branches:
      - "main"
    tags-ignore:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to ghcr
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker login ghcr.io -u chestercodes -p $GITHUB_TOKEN

      - name: Pull sdk image
        run: docker pull mcr.microsoft.com/dotnet/sdk:8.0
        shell: pwsh

      - name: Pull runtime image
        run: docker pull mcr.microsoft.com/dotnet/aspnet:8.0
        shell: pwsh

      - name: Set image tag
        run: IMAGE_TAG=$(date +"v%y%m%d%H%M%S") && echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_ENV"

      - name: Build images in parallel
        run: docker compose -f docker/build.yaml build --parallel
        working-directory: app

      - name: push images
        run: docker compose -f docker/build.yaml push
        working-directory: app

      - name: Create git tag
        run: |
          git tag $IMAGE_TAG
      - name: Push git tag
        run: git push origin $IMAGE_TAG
